// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: keymanager/km_common/proto/key_claims.proto

package keymanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyType int32

const (
	KeyType_KEY_TYPE_UNSPECIFIED KeyType = 0
	// A standard HPKE binding key-pair used for internal isolation.
	KeyType_KEY_TYPE_VM_PROTECTION_BINDING KeyType = 1
	// A KEM key-pair managed by the Key Protection Service.
	KeyType_KEY_TYPE_VM_PROTECTION_KEY KeyType = 2
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "KEY_TYPE_UNSPECIFIED",
		1: "KEY_TYPE_VM_PROTECTION_BINDING",
		2: "KEY_TYPE_VM_PROTECTION_KEY",
	}
	KeyType_value = map[string]int32{
		"KEY_TYPE_UNSPECIFIED":           0,
		"KEY_TYPE_VM_PROTECTION_BINDING": 1,
		"KEY_TYPE_VM_PROTECTION_KEY":     2,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_keymanager_km_common_proto_key_claims_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_keymanager_km_common_proto_key_claims_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{0}
}

type KeyProtectionMechanism int32

const (
	KeyProtectionMechanism_KEY_PROTECTION_MECHANISM_UNSPECIFIED KeyProtectionMechanism = 0
	// The key is held by the Workload Services Daemon, and is endorsed by a single CVM
	// attestation.
	KeyProtectionMechanism_DEFAULT KeyProtectionMechanism = 1
	// The key is held by the Key Protection Services VM, and is endorsed by a pair of CVM
	// attestations, from the Workload Services Daemon and Key Protection VM.
	KeyProtectionMechanism_KEY_PROTECTION_VM KeyProtectionMechanism = 2
	// Emulated KEY_PROTECTION_VM mode.
	KeyProtectionMechanism_KEY_PROTECTION_VM_EMULATED KeyProtectionMechanism = 3
)

// Enum value maps for KeyProtectionMechanism.
var (
	KeyProtectionMechanism_name = map[int32]string{
		0: "KEY_PROTECTION_MECHANISM_UNSPECIFIED",
		1: "DEFAULT",
		2: "KEY_PROTECTION_VM",
		3: "KEY_PROTECTION_VM_EMULATED",
	}
	KeyProtectionMechanism_value = map[string]int32{
		"KEY_PROTECTION_MECHANISM_UNSPECIFIED": 0,
		"DEFAULT":                              1,
		"KEY_PROTECTION_VM":                    2,
		"KEY_PROTECTION_VM_EMULATED":           3,
	}
)

func (x KeyProtectionMechanism) Enum() *KeyProtectionMechanism {
	p := new(KeyProtectionMechanism)
	*p = x
	return p
}

func (x KeyProtectionMechanism) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyProtectionMechanism) Descriptor() protoreflect.EnumDescriptor {
	return file_keymanager_km_common_proto_key_claims_proto_enumTypes[1].Descriptor()
}

func (KeyProtectionMechanism) Type() protoreflect.EnumType {
	return &file_keymanager_km_common_proto_key_claims_proto_enumTypes[1]
}

func (x KeyProtectionMechanism) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyProtectionMechanism.Descriptor instead.
func (KeyProtectionMechanism) EnumDescriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{1}
}

// Used to refer to key instances held by various daemons.
type KeyHandle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handle string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
}

func (x *KeyHandle) Reset() {
	*x = KeyHandle{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyHandle) ProtoMessage() {}

func (x *KeyHandle) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyHandle.ProtoReflect.Descriptor instead.
func (*KeyHandle) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{0}
}

func (x *KeyHandle) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

// GetKeyClaimsRequest defines the input required to retrieve claims for a key.
type GetKeyClaimsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique identifier (UUID) for the key.
	KeyHandle *KeyHandle `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	// The type of key (Binding or KEM) which determines the claim format.
	KeyType KeyType `protobuf:"varint,2,opt,name=key_type,json=keyType,proto3,enum=keymanager.KeyType" json:"key_type,omitempty"`
}

func (x *GetKeyClaimsRequest) Reset() {
	*x = GetKeyClaimsRequest{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyClaimsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyClaimsRequest) ProtoMessage() {}

func (x *GetKeyClaimsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyClaimsRequest.ProtoReflect.Descriptor instead.
func (*GetKeyClaimsRequest) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{1}
}

func (x *GetKeyClaimsRequest) GetKeyHandle() *KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *GetKeyClaimsRequest) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_KEY_TYPE_UNSPECIFIED
}

type KemPublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm KemAlgorithm `protobuf:"varint,1,opt,name=algorithm,proto3,enum=keymanager.KemAlgorithm" json:"algorithm,omitempty"`
	PublicKey []byte       `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // `Npk` bytes long; see the KemAlgorithm definition.
}

func (x *KemPublicKey) Reset() {
	*x = KemPublicKey{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KemPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KemPublicKey) ProtoMessage() {}

func (x *KemPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KemPublicKey.ProtoReflect.Descriptor instead.
func (*KemPublicKey) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{2}
}

func (x *KemPublicKey) GetAlgorithm() KemAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

func (x *KemPublicKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type HpkePublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm *HpkeAlgorithm `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PublicKey []byte         `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // `Npk` bytes long. Raw bytes.
}

func (x *HpkePublicKey) Reset() {
	*x = HpkePublicKey{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HpkePublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HpkePublicKey) ProtoMessage() {}

func (x *HpkePublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HpkePublicKey.ProtoReflect.Descriptor instead.
func (*HpkePublicKey) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{3}
}

func (x *HpkePublicKey) GetAlgorithm() *HpkeAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *HpkePublicKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// The results of an Encaps operation.
type KemCiphertext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm  KemAlgorithm `protobuf:"varint,1,opt,name=algorithm,proto3,enum=keymanager.KemAlgorithm" json:"algorithm,omitempty"`
	Ciphertext []byte       `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // `Nenc` bytes long.
}

func (x *KemCiphertext) Reset() {
	*x = KemCiphertext{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KemCiphertext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KemCiphertext) ProtoMessage() {}

func (x *KemCiphertext) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KemCiphertext.ProtoReflect.Descriptor instead.
func (*KemCiphertext) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{4}
}

func (x *KemCiphertext) GetAlgorithm() KemAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

func (x *KemCiphertext) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// The results of a Decaps operation.
type KemSharedSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm KemAlgorithm `protobuf:"varint,1,opt,name=algorithm,proto3,enum=keymanager.KemAlgorithm" json:"algorithm,omitempty"`
	Secret    []byte       `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"` // `Nsecret` bytes long.
}

func (x *KemSharedSecret) Reset() {
	*x = KemSharedSecret{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KemSharedSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KemSharedSecret) ProtoMessage() {}

func (x *KemSharedSecret) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KemSharedSecret.ProtoReflect.Descriptor instead.
func (*KemSharedSecret) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{5}
}

func (x *KemSharedSecret) GetAlgorithm() KemAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return KemAlgorithm_KEM_ALGORITHM_UNSPECIFIED
}

func (x *KemSharedSecret) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type HpkePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm         *HpkeAlgorithm `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KemCiphertext     []byte         `protobuf:"bytes,2,opt,name=kem_ciphertext,json=kemCiphertext,proto3" json:"kem_ciphertext,omitempty"`             // `Nenc` bytes long.
	PayloadCiphertext []byte         `protobuf:"bytes,3,opt,name=payload_ciphertext,json=payloadCiphertext,proto3" json:"payload_ciphertext,omitempty"` // Encrypted data.
	AuthenticationTag []byte         `protobuf:"bytes,4,opt,name=authentication_tag,json=authenticationTag,proto3" json:"authentication_tag,omitempty"` // `Nt` bytes long.
}

func (x *HpkePayload) Reset() {
	*x = HpkePayload{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HpkePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HpkePayload) ProtoMessage() {}

func (x *HpkePayload) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HpkePayload.ProtoReflect.Descriptor instead.
func (*HpkePayload) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{6}
}

func (x *HpkePayload) GetAlgorithm() *HpkeAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *HpkePayload) GetKemCiphertext() []byte {
	if x != nil {
		return x.KemCiphertext
	}
	return nil
}

func (x *HpkePayload) GetPayloadCiphertext() []byte {
	if x != nil {
		return x.PayloadCiphertext
	}
	return nil
}

func (x *HpkePayload) GetAuthenticationTag() []byte {
	if x != nil {
		return x.AuthenticationTag
	}
	return nil
}

type KeyClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Claims:
	//
	//	*KeyClaims_VmBindingClaims
	//	*KeyClaims_VmKeyClaims
	Claims isKeyClaims_Claims `protobuf_oneof:"claims"`
}

func (x *KeyClaims) Reset() {
	*x = KeyClaims{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyClaims) ProtoMessage() {}

func (x *KeyClaims) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyClaims.ProtoReflect.Descriptor instead.
func (*KeyClaims) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{7}
}

func (m *KeyClaims) GetClaims() isKeyClaims_Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (x *KeyClaims) GetVmBindingClaims() *KeyClaims_VmProtectionBindingClaims {
	if x, ok := x.GetClaims().(*KeyClaims_VmBindingClaims); ok {
		return x.VmBindingClaims
	}
	return nil
}

func (x *KeyClaims) GetVmKeyClaims() *KeyClaims_VmProtectionKeyClaims {
	if x, ok := x.GetClaims().(*KeyClaims_VmKeyClaims); ok {
		return x.VmKeyClaims
	}
	return nil
}

type isKeyClaims_Claims interface {
	isKeyClaims_Claims()
}

type KeyClaims_VmBindingClaims struct {
	VmBindingClaims *KeyClaims_VmProtectionBindingClaims `protobuf:"bytes,1,opt,name=vm_binding_claims,json=vmBindingClaims,proto3,oneof"`
}

type KeyClaims_VmKeyClaims struct {
	VmKeyClaims *KeyClaims_VmProtectionKeyClaims `protobuf:"bytes,2,opt,name=vm_key_claims,json=vmKeyClaims,proto3,oneof"`
}

func (*KeyClaims_VmBindingClaims) isKeyClaims_Claims() {}

func (*KeyClaims_VmKeyClaims) isKeyClaims_Claims() {}

type KeyClaims_VmProtectionBindingClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The workload attests that it controls the corresponding private key.
	BindingPubKey *HpkePublicKey `protobuf:"bytes,1,opt,name=binding_pub_key,json=bindingPubKey,proto3" json:"binding_pub_key,omitempty"`
}

func (x *KeyClaims_VmProtectionBindingClaims) Reset() {
	*x = KeyClaims_VmProtectionBindingClaims{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyClaims_VmProtectionBindingClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyClaims_VmProtectionBindingClaims) ProtoMessage() {}

func (x *KeyClaims_VmProtectionBindingClaims) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyClaims_VmProtectionBindingClaims.ProtoReflect.Descriptor instead.
func (*KeyClaims_VmProtectionBindingClaims) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{7, 0}
}

func (x *KeyClaims_VmProtectionBindingClaims) GetBindingPubKey() *HpkePublicKey {
	if x != nil {
		return x.BindingPubKey
	}
	return nil
}

type KeyClaims_VmProtectionKeyClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Key Protection Service attests that it controls the KEM private key, and that
	// it will encrypt all resulting shared secrets to the binding key.
	KemPubKey     *KemPublicKey  `protobuf:"bytes,1,opt,name=kem_pub_key,json=kemPubKey,proto3" json:"kem_pub_key,omitempty"`
	BindingPubKey *HpkePublicKey `protobuf:"bytes,2,opt,name=binding_pub_key,json=bindingPubKey,proto3" json:"binding_pub_key,omitempty"`
	// The remaining time until the Key Protection Service will autonomously delete its
	// KEM keypair.
	RemainingLifespan *durationpb.Duration `protobuf:"bytes,3,opt,name=remaining_lifespan,json=remainingLifespan,proto3" json:"remaining_lifespan,omitempty"`
}

func (x *KeyClaims_VmProtectionKeyClaims) Reset() {
	*x = KeyClaims_VmProtectionKeyClaims{}
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyClaims_VmProtectionKeyClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyClaims_VmProtectionKeyClaims) ProtoMessage() {}

func (x *KeyClaims_VmProtectionKeyClaims) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_km_common_proto_key_claims_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyClaims_VmProtectionKeyClaims.ProtoReflect.Descriptor instead.
func (*KeyClaims_VmProtectionKeyClaims) Descriptor() ([]byte, []int) {
	return file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP(), []int{7, 1}
}

func (x *KeyClaims_VmProtectionKeyClaims) GetKemPubKey() *KemPublicKey {
	if x != nil {
		return x.KemPubKey
	}
	return nil
}

func (x *KeyClaims_VmProtectionKeyClaims) GetBindingPubKey() *HpkePublicKey {
	if x != nil {
		return x.BindingPubKey
	}
	return nil
}

func (x *KeyClaims_VmProtectionKeyClaims) GetRemainingLifespan() *durationpb.Duration {
	if x != nil {
		return x.RemainingLifespan
	}
	return nil
}

var File_keymanager_km_common_proto_key_claims_proto protoreflect.FileDescriptor

var file_keymanager_km_common_proto_key_claims_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x6b, 0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x6b, 0x6d, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x79,
	0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6b,
	0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2b, 0x6b, 0x65, 0x79, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x6b, 0x6d, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x7b, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x4b, 0x65, 0x79, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x4b, 0x65, 0x79, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x09, 0x6b,
	0x65, 0x79, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6b, 0x65, 0x79,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x65, 0x0a, 0x0c, 0x4b, 0x65, 0x6d, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f,
	0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6b, 0x65,
	0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4b, 0x65, 0x6d, 0x41, 0x6c, 0x67, 0x6f,
	0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22,
	0x67, 0x0a, 0x0d, 0x48, 0x70, 0x6b, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x37, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x48, 0x70, 0x6b, 0x65, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x09,
	0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x67, 0x0a, 0x0d, 0x4b, 0x65, 0x6d, 0x43,
	0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x61, 0x6c, 0x67,
	0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6b,
	0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4b, 0x65, 0x6d, 0x41, 0x6c, 0x67,
	0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x61, 0x0a, 0x0f, 0x4b, 0x65, 0x6d, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6b, 0x65, 0x79, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x4b, 0x65, 0x6d, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x22, 0xcb, 0x01, 0x0a, 0x0b, 0x48, 0x70, 0x6b, 0x65, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x65, 0x79, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x48, 0x70, 0x6b, 0x65, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x25, 0x0a,
	0x0e, 0x6b, 0x65, 0x6d, 0x5f, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x6b, 0x65, 0x6d, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x11, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x11, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x61, 0x67, 0x22, 0x88, 0x04, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73,
	0x12, 0x5d, 0x0a, 0x11, 0x76, 0x6d, 0x5f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x63,
	0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6b, 0x65,
	0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4b, 0x65, 0x79, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x73, 0x2e, 0x56, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x0f,
	0x76, 0x6d, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12,
	0x51, 0x0a, 0x0d, 0x76, 0x6d, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6b, 0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x4b, 0x65, 0x79, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x2e, 0x56, 0x6d,
	0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x76, 0x6d, 0x4b, 0x65, 0x79, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x73, 0x1a, 0x5e, 0x0a, 0x19, 0x56, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12,
	0x41, 0x0a, 0x0f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x75, 0x62, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x65, 0x79, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x48, 0x70, 0x6b, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x52, 0x0d, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x1a, 0xde, 0x01, 0x0a, 0x15, 0x56, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x38, 0x0a, 0x0b,
	0x6b, 0x65, 0x6d, 0x5f, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4b,
	0x65, 0x6d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x6b, 0x65, 0x6d,
	0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x41, 0x0a, 0x0f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6b, 0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x48, 0x70, 0x6b,
	0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x0d, 0x62, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x48, 0x0a, 0x12, 0x72, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x11, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x66, 0x65, 0x73,
	0x70, 0x61, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x2a, 0x67, 0x0a,
	0x07, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x4b, 0x45, 0x59, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x22, 0x0a, 0x1e, 0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x56,
	0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x42, 0x49, 0x4e,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x56, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x4b, 0x45, 0x59, 0x10, 0x02, 0x2a, 0x86, 0x01, 0x0a, 0x16, 0x4b, 0x65, 0x79, 0x50, 0x72,
	0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x69, 0x73,
	0x6d, 0x12, 0x28, 0x0a, 0x24, 0x4b, 0x45, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x45, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x43, 0x48, 0x41, 0x4e, 0x49, 0x53, 0x4d, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4b, 0x45, 0x59, 0x5f,
	0x50, 0x52, 0x4f, 0x54, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x56, 0x4d, 0x10, 0x02, 0x12,
	0x1e, 0x0a, 0x1a, 0x4b, 0x45, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x45, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x56, 0x4d, 0x5f, 0x45, 0x4d, 0x55, 0x4c, 0x41, 0x54, 0x45, 0x44, 0x10, 0x03, 0x42,
	0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x70, 0x6d, 0x2d, 0x74, 0x6f, 0x6f, 0x6c,
	0x73, 0x2f, 0x6b, 0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x6b, 0x6d, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6b, 0x65, 0x79,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keymanager_km_common_proto_key_claims_proto_rawDescOnce sync.Once
	file_keymanager_km_common_proto_key_claims_proto_rawDescData = file_keymanager_km_common_proto_key_claims_proto_rawDesc
)

func file_keymanager_km_common_proto_key_claims_proto_rawDescGZIP() []byte {
	file_keymanager_km_common_proto_key_claims_proto_rawDescOnce.Do(func() {
		file_keymanager_km_common_proto_key_claims_proto_rawDescData = protoimpl.X.CompressGZIP(file_keymanager_km_common_proto_key_claims_proto_rawDescData)
	})
	return file_keymanager_km_common_proto_key_claims_proto_rawDescData
}

var file_keymanager_km_common_proto_key_claims_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_keymanager_km_common_proto_key_claims_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_keymanager_km_common_proto_key_claims_proto_goTypes = []any{
	(KeyType)(0),                                // 0: keymanager.KeyType
	(KeyProtectionMechanism)(0),                 // 1: keymanager.KeyProtectionMechanism
	(*KeyHandle)(nil),                           // 2: keymanager.KeyHandle
	(*GetKeyClaimsRequest)(nil),                 // 3: keymanager.GetKeyClaimsRequest
	(*KemPublicKey)(nil),                        // 4: keymanager.KemPublicKey
	(*HpkePublicKey)(nil),                       // 5: keymanager.HpkePublicKey
	(*KemCiphertext)(nil),                       // 6: keymanager.KemCiphertext
	(*KemSharedSecret)(nil),                     // 7: keymanager.KemSharedSecret
	(*HpkePayload)(nil),                         // 8: keymanager.HpkePayload
	(*KeyClaims)(nil),                           // 9: keymanager.KeyClaims
	(*KeyClaims_VmProtectionBindingClaims)(nil), // 10: keymanager.KeyClaims.VmProtectionBindingClaims
	(*KeyClaims_VmProtectionKeyClaims)(nil),     // 11: keymanager.KeyClaims.VmProtectionKeyClaims
	(KemAlgorithm)(0),                           // 12: keymanager.KemAlgorithm
	(*HpkeAlgorithm)(nil),                       // 13: keymanager.HpkeAlgorithm
	(*durationpb.Duration)(nil),                 // 14: google.protobuf.Duration
}
var file_keymanager_km_common_proto_key_claims_proto_depIdxs = []int32{
	2,  // 0: keymanager.GetKeyClaimsRequest.key_handle:type_name -> keymanager.KeyHandle
	0,  // 1: keymanager.GetKeyClaimsRequest.key_type:type_name -> keymanager.KeyType
	12, // 2: keymanager.KemPublicKey.algorithm:type_name -> keymanager.KemAlgorithm
	13, // 3: keymanager.HpkePublicKey.algorithm:type_name -> keymanager.HpkeAlgorithm
	12, // 4: keymanager.KemCiphertext.algorithm:type_name -> keymanager.KemAlgorithm
	12, // 5: keymanager.KemSharedSecret.algorithm:type_name -> keymanager.KemAlgorithm
	13, // 6: keymanager.HpkePayload.algorithm:type_name -> keymanager.HpkeAlgorithm
	10, // 7: keymanager.KeyClaims.vm_binding_claims:type_name -> keymanager.KeyClaims.VmProtectionBindingClaims
	11, // 8: keymanager.KeyClaims.vm_key_claims:type_name -> keymanager.KeyClaims.VmProtectionKeyClaims
	5,  // 9: keymanager.KeyClaims.VmProtectionBindingClaims.binding_pub_key:type_name -> keymanager.HpkePublicKey
	4,  // 10: keymanager.KeyClaims.VmProtectionKeyClaims.kem_pub_key:type_name -> keymanager.KemPublicKey
	5,  // 11: keymanager.KeyClaims.VmProtectionKeyClaims.binding_pub_key:type_name -> keymanager.HpkePublicKey
	14, // 12: keymanager.KeyClaims.VmProtectionKeyClaims.remaining_lifespan:type_name -> google.protobuf.Duration
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_keymanager_km_common_proto_key_claims_proto_init() }
func file_keymanager_km_common_proto_key_claims_proto_init() {
	if File_keymanager_km_common_proto_key_claims_proto != nil {
		return
	}
	file_keymanager_km_common_proto_algorithms_proto_init()
	file_keymanager_km_common_proto_key_claims_proto_msgTypes[7].OneofWrappers = []any{
		(*KeyClaims_VmBindingClaims)(nil),
		(*KeyClaims_VmKeyClaims)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keymanager_km_common_proto_key_claims_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keymanager_km_common_proto_key_claims_proto_goTypes,
		DependencyIndexes: file_keymanager_km_common_proto_key_claims_proto_depIdxs,
		EnumInfos:         file_keymanager_km_common_proto_key_claims_proto_enumTypes,
		MessageInfos:      file_keymanager_km_common_proto_key_claims_proto_msgTypes,
	}.Build()
	File_keymanager_km_common_proto_key_claims_proto = out.File
	file_keymanager_km_common_proto_key_claims_proto_rawDesc = nil
	file_keymanager_km_common_proto_key_claims_proto_goTypes = nil
	file_keymanager_km_common_proto_key_claims_proto_depIdxs = nil
}
